# Generated by Django 3.0.5 on 2020-06-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gig', 'gig'), ('tour', 'tour'), ('party', 'party'), ('training', 'training'), ('recording', 'recording')], default='gig', max_length=27)),
                ('controller', models.CharField(default='Gig', max_length=15)),
                ('slots_required', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bands_involved', models.ManyToManyField(to='brand.Band')),
                ('brands_involved', models.ManyToManyField(to='brand.Brand')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event')),
            ],
        ),
    ]
