# Generated by Django 3.0.5 on 2020-06-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('brand', '0002_auto_20200604_1017'),
        ('locations', '0001_initial'),
        ('people', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='parties_involved',
            field=models.ManyToManyField(to='people.Person'),
        ),
        migrations.AddField(
            model_name='eventslot',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='acts',
            field=models.ManyToManyField(to='brand.Band'),
        ),
        migrations.AddField(
            model_name='event',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='genres.Genre'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(to='people.Person'),
        ),
    ]
