# Generated by Django 3.0.5 on 2020-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200503_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='class_name',
            field=models.CharField(default='Gig', max_length=15),
        ),
    ]
