# Generated by Django 3.0.5 on 2020-05-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventtype_slots_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtype',
            old_name='class_name',
            new_name='controller',
        ),
    ]
