# Generated by Django 3.0.5 on 2020-06-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('colour', models.CharField(default='blue', max_length=15)),
                ('influence', models.PositiveSmallIntegerField(default=0)),
                ('money', models.SmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=127)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
