# Generated by Django 3.0.5 on 2020-06-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
        ('brand', '0001_initial'),
        ('genres', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='events_unlocked',
            field=models.ManyToManyField(to='events.EventType'),
        ),
        migrations.AddField(
            model_name='brand',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='game.Game'),
        ),
        migrations.AddField(
            model_name='band',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='genres.Genre'),
        ),
        migrations.AddField(
            model_name='band',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
    ]
