# Generated by Django 3.0.5 on 2020-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_auto_20200604_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='brand',
            name='money',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='brand',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recordlabel',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
