# Generated by Django 3.0.5 on 2020-05-02 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200502_1822'),
        ('brand', '0003_auto_20200502_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starts_at',
        ),
        migrations.AddField(
            model_name='band',
            name='musicians',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Job'),
        ),
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('gig', 'gig'), ('tour', 'tour'), ('party', 'party'), ('training', 'training'), ('recording', 'recording')], default='gig', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(to='people.Person'),
        ),
    ]
