# Generated by Django 3.0.5 on 2020-05-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20200502_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('gig', 'gig'), ('tour', 'tour'), ('party', 'party'), ('training', 'training'), ('recording', 'recording')], default='gig', max_length=27),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='recordlabel',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
