# Generated by Django 3.0.5 on 2020-05-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20200502_2133'),
        ('brand', '0005_auto_20200502_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='musicians',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
    ]
