# Generated by Django 3.0.5 on 2020-05-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_auto_20200502_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='musicians',
        ),
    ]
