# Generated by Django 3.0.5 on 2020-05-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('brand', '0007_remove_band_musicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='game.Game'),
        ),
    ]
