# Generated by Django 3.0.5 on 2020-05-03 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_brand_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='event',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='recordlabel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Brand'),
        ),
    ]
