# Generated by Django 3.0.5 on 2020-05-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_auto_20200503_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='acts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='event',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='people',
        ),
    ]
