# Generated by Django 3.0.5 on 2020-05-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_auto_20200503_1237'),
        ('locations', '0010_auto_20200503_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
