# Generated by Django 3.0.5 on 2020-05-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200503_1515'),
        ('brand', '0011_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='events_unlocked',
            field=models.ManyToManyField(to='events.EventType'),
        ),
    ]
