# Generated by Django 3.0.5 on 2020-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0012_brand_events_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='colour',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow')], default=0, max_length=15),
        ),
    ]
