# Generated by Django 3.0.5 on 2020-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0013_brand_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='colour',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green')], default=0, max_length=15),
        ),
    ]
