# Generated by Django 3.0.5 on 2020-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0014_auto_20200503_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='colour',
            field=models.CharField(default='blue', max_length=15),
        ),
    ]
