# Generated by Django 3.0.5 on 2020-05-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_auto_20200503_1803'),
        ('brand', '0015_auto_20200503_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='brand',
            name='money',
            field=models.SmallIntegerField(default=100),
        ),
    ]
