# Generated by Django 3.0.5 on 2020-05-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0017_auto_20200510_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='influence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
