# Generated by Django 3.0.5 on 2020-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('year_invented', models.PositiveSmallIntegerField()),
                ('colour', models.CharField(default='#EEEEEE', max_length=31)),
            ],
        ),
    ]
