# Generated by Django 3.0.5 on 2020-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='colour',
            field=models.CharField(default='#EEEEEE', max_length=31),
        ),
    ]
