# Generated by Django 3.0.5 on 2020-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('affects', models.CharField(default="'global", max_length=255)),
                ('effects', models.CharField(default="{'popularity': 0}", max_length=255)),
                ('category', models.CharField(blank=True, choices=[('event', 'event'), ('instruments', 'instruments'), ('location', 'location')], max_length=27, null=True)),
                ('progress', models.CharField(choices=[('event', 'event'), ('instruments', 'instruments'), ('location', 'location')], default=0, max_length=27)),
                ('brand', models.ManyToManyField(related_name='technologies', to='brand.Brand')),
            ],
        ),
    ]
