# Generated by Django 3.0.5 on 2020-05-02 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech',
            old_name='title',
            new_name='name',
        ),
    ]
