# Generated by Django 3.0.5 on 2020-08-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='affects',
            field=models.CharField(default="'global'", max_length=255),
        ),
    ]
