# Generated by Django 3.0.5 on 2020-05-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('tech', '0002_auto_20200502_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='affects',
            field=models.CharField(default="'global", max_length=255),
        ),
        migrations.AddField(
            model_name='tech',
            name='cost_per_turn',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tech',
            name='effects',
            field=models.CharField(default="{'influence': 0}", max_length=255),
        ),
        migrations.AddField(
            model_name='tech',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tech', to='game.Game'),
        ),
        migrations.AddField(
            model_name='tech',
            name='lasts_for',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
