# Generated by Django 3.0.5 on 2020-08-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20200809_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tech',
            name='pack',
            field=models.ManyToManyField(blank=True, null=True, related_name='components', to='tech.TechPack'),
        ),
    ]
