# Generated by Django 3.0.5 on 2020-08-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_auto_20200809_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('wallpaper', 'wallpaper'), ('flooring', 'flooring'), ('bar', 'bar')], max_length=27, null=True),
        ),
    ]
