# Generated by Django 3.0.5 on 2020-05-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_auto_20200502_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='cost_per_turn',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='game',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='lasts_for',
        ),
    ]
