# Generated by Django 3.0.5 on 2020-05-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_auto_20200503_0026'),
        ('tech', '0005_tech_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='brand',
            field=models.ManyToManyField(related_name='technologies', to='brand.Brand'),
        ),
    ]
