# Generated by Django 3.0.5 on 2020-08-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_delete_locationfeature'),
        ('tech', '0005_remove_tech_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('filepath', models.CharField(max_length=127)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('path_d', models.CharField(blank=True, max_length=2500, null=True)),
                ('layer', models.CharField(blank=True, max_length=1, null=True)),
                ('category', models.CharField(blank=True, choices=[('wallpaper', 'wallpaper'), ('flooring', 'flooring'), ('bar', 'bar'), ('equipment', 'equipment'), ('music equipment', 'music equipment')], max_length=27, null=True)),
                ('locations', models.ManyToManyField(blank=True, null=True, related_name='features', to='locations.Location')),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech.Tech')),
            ],
            options={
                'ordering': ['layer'],
            },
        ),
    ]
