# Generated by Django 3.0.5 on 2020-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_locationfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfeature',
            name='x',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationfeature',
            name='y',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
