# Generated by Django 3.0.5 on 2020-05-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_auto_20200503_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech',
            old_name='brand',
            new_name='brands',
        ),
    ]
