# Generated by Django 3.0.5 on 2020-05-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_auto_20200503_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech',
            old_name='brands',
            new_name='brand',
        ),
    ]
