# Generated by Django 3.0.5 on 2020-08-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_auto_20200812_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfeature',
            name='has_border',
            field=models.BooleanField(default=False),
        ),
    ]
