# Generated by Django 3.0.5 on 2020-05-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barstaff',
            options={'verbose_name_plural': 'bar staff (job)'},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name_plural': 'musicians (job)'},
        ),
        migrations.AlterModelOptions(
            name='promoter',
            options={'verbose_name_plural': 'promoters (job)'},
        ),
        migrations.AlterModelOptions(
            name='roadie',
            options={'verbose_name_plural': 'roadies (job)'},
        ),
        migrations.AlterModelOptions(
            name='techie',
            options={'verbose_name_plural': 'techies (job)'},
        ),
        migrations.AlterModelOptions(
            name='venueowner',
            options={'verbose_name_plural': 'venue owners (job)'},
        ),
        migrations.AddField(
            model_name='barstaff',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AddField(
            model_name='musician',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AddField(
            model_name='promoter',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AddField(
            model_name='roadie',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AddField(
            model_name='techie',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
    ]
