# Generated by Django 3.0.5 on 2020-06-06 18:52

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20200606_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hair_detail',
            field=models.CharField(default=people.models.HAIR_COLORS, max_length=7),
        ),
        migrations.AddField(
            model_name='person',
            name='skin_color',
            field=models.CharField(default=['#ffc999', '#754b32'], max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='hair_color',
            field=models.CharField(default=people.models.HAIR_COLORS, max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_color',
            field=models.CharField(default=['#280c38'], max_length=7),
        ),
    ]
