# Generated by Django 3.0.5 on 2020-05-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20200502_1740'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0001_initial'),
        ('people', '0002_auto_20200502_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barstaff',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='barstaff',
            name='person',
        ),
        migrations.RemoveField(
            model_name='barstaff',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='person',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='person',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='person',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='roadie',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='roadie',
            name='person',
        ),
        migrations.RemoveField(
            model_name='roadie',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='techie',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='techie',
            name='person',
        ),
        migrations.RemoveField(
            model_name='techie',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='venueowner',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='venueowner',
            name='person',
        ),
        migrations.RemoveField(
            model_name='venueowner',
            name='workplace',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('bar s', 'bar staff'), ('techi', 'techie'), ('roadi', 'roadie'), ('music', 'musician'), ('promo', 'promoter'), ('venue', 'venue owner')], max_length=5)),
                ('role_id', models.PositiveIntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Brand')),
                ('role_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Job'),
        ),
    ]
