# Generated by Django 3.0.5 on 2020-06-07 09:35

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200606_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jacket_color',
            field=models.CharField(default=people.models.CLOTHING_COLORS, max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='hair_style',
            field=models.CharField(default=people.models.HAIR_STYLES, max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_color',
            field=models.CharField(default=people.models.CLOTHING_COLORS, max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_detail',
            field=models.CharField(default=people.models.CLOTHING_COLORS, max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='skin_color',
            field=models.CharField(default=people.models.SKIN_COLORS, max_length=7),
        ),
    ]
