# Generated by Django 3.0.5 on 2020-06-07 11:40

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200607_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='shirt_style',
            field=models.CharField(default=people.models.SHIRT_STYLES, max_length=1),
        ),
    ]
