# Generated by Django 3.0.5 on 2020-05-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200502_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='role_obj',
        ),
    ]
