# Generated by Django 3.0.5 on 2020-05-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20200502_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='crowds',
        ),
        migrations.AlterField(
            model_name='crowd',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowds', to='people.Population'),
        ),
    ]
