# Generated by Django 3.0.5 on 2020-06-14 14:13

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20200607_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jacket_style',
            field=models.CharField(default=people.models.JACKET_STYLES, max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='happiness',
            field=models.CharField(choices=[('0', "majorly foo'd off"), ('1', 'really???'), ('2', 'this sucks!!'), ('3', 'meh.'), ('4', "i mean, life's been better"), ('5', 'taking it as it comes'), ('6', 'pretty chill'), ('7', 'in the vibe!'), ('8', 'yeahhh! ROCK OONN!'), ('9', 'cloud 9, this is nirvana, man...')], default='7', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
