# Generated by Django 3.0.5 on 2020-05-02 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20200502_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='population',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('bar staff', 'bar staff'), ('techie', 'techie'), ('roadie', 'roadie'), ('musician', 'musician'), ('promoter', 'promoter'), ('venue owner', 'venue owner')], max_length=27),
        ),
    ]
