# Generated by Django 3.0.5 on 2020-05-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_remove_band_musicians'),
        ('people', '0009_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicians', to='brand.Band'),
        ),
    ]
