# Generated by Django 3.0.5 on 2020-05-02 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_remove_band_musicians'),
        ('people', '0012_auto_20200502_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicians', to='brand.Band'),
        ),
    ]
