# Generated by Django 3.0.5 on 2020-05-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20200502_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('bar staff', 'bar staff'), ('techie', 'techie'), ('roadie', 'roadie'), ('musician', 'musician'), ('teacher', 'teacher'), ('promoter', 'promoter'), ('venue owner', 'venue owner')], max_length=27),
        ),
    ]
