# Generated by Django 3.0.5 on 2020-05-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20200502_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Cool cat', 'verbose_name_plural': 'People in the industry'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'contacts'},
        ),
    ]
