# Generated by Django 3.0.5 on 2020-05-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20200502_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='people.Job'),
        ),
    ]
