# Generated by Django 3.0.5 on 2020-05-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_district_population'),
        ('people', '0016_auto_20200502_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowd',
            name='population',
        ),
        migrations.AddField(
            model_name='crowd',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crowds', to='locations.District'),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='locations.Location'),
        ),
        migrations.DeleteModel(
            name='Population',
        ),
    ]
