# Generated by Django 3.0.5 on 2020-05-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20200503_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='happiness',
            field=models.CharField(default='6', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='influence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
