# Generated by Django 3.0.5 on 2020-05-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_auto_20200520_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='happiness',
            field=models.CharField(choices=[('0', "majorly foo'd off"), ('1', 'really???'), ('2', 'this sucks!!'), ('3', 'meh.'), ('4', "i mean, life's been better"), ('5', 'taking it as it comes'), ('6', 'pretty chill'), ('7', 'in the vibe!'), ('8', 'yeahhh! ROCK OONN!'), ('9', 'cloud 9, this is nirvana, man...')], default='6', max_length=1),
        ),
    ]
