# Generated by Django 3.0.5 on 2020-05-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20200502_1823'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slots_available',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parties_involved', models.ManyToManyField(to='people.Person')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='slots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.EventSlot'),
        ),
    ]
