# Generated by Django 3.0.5 on 2020-05-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_auto_20200502_2110'),
        ('locations', '0002_auto_20200502_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='bands_involved',
            field=models.ManyToManyField(to='brand.Band'),
        ),
        migrations.AddField(
            model_name='eventslot',
            name='brands_involved',
            field=models.ManyToManyField(to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='eventslot',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Event'),
        ),
        migrations.AddField(
            model_name='eventslot',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('music venue', 'music venue'), ('bar', 'bar'), ('park', 'park'), ('record store', 'record store'), ('musical instrument shop', 'musical instrument shop'), ('music lessons', 'music lessons'), ('recording studio', 'recording studio'), ('promo office', 'promo office'), ('workshop', 'workshop'), ('band house', 'band house')], max_length=27),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
