# Generated by Django 3.0.5 on 2020-06-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('locations', '0003_auto_20200604_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='genres.Genre'),
        ),
    ]
