# Generated by Django 3.0.5 on 2020-05-02 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('locations', '0003_auto_20200502_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Game'),
        ),
    ]
