# Generated by Django 3.0.5 on 2020-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200604_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='category',
            field=models.CharField(choices=[('venue with stage', 'venue with stage'), ('venue without stage', 'venue without stage'), ('pub or cafe', 'pub or cafe'), ('shop', 'shop'), ('public place', 'public place'), ('private place', 'private place'), ('training or work', 'training or work')], max_length=31),
        ),
    ]
