# Generated by Django 3.0.5 on 2020-05-02 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('locations', '0004_city_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='game.Game'),
        ),
    ]
