# Generated by Django 3.0.5 on 2020-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200604_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='district',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='name',
            field=models.CharField(choices=[('concert hall', 'concert hall'), ('gig venue', 'gig venue'), ('music bar', 'music bar'), ('local pub', 'local pub'), ('club', 'club'), ('record store', 'record store'), ('musical instrument shop', 'musical instrument shop'), ('music school', 'music school'), ('recording studio', 'recording studio'), ('promo office', 'promo office'), ('workshop', 'workshop'), ('band house', 'band house'), ('park', 'park'), ('empty plot', 'empty plot')], max_length=31),
        ),
    ]
