# Generated by Django 3.0.5 on 2020-05-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20200502_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
    ]
