# Generated by Django 3.0.5 on 2020-06-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20200614_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('filepath', models.CharField(max_length=127)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('location', models.ManyToManyField(related_name='features', to='locations.Location')),
            ],
        ),
    ]
