# Generated by Django 3.0.5 on 2020-05-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20200503_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='population',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
