# Generated by Django 3.0.5 on 2020-06-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_locationfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfeature',
            name='path_d',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
