# Generated by Django 3.0.5 on 2020-05-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('locations', '0009_district_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.EventSlot'),
        ),
        migrations.DeleteModel(
            name='EventSlot',
        ),
    ]
