# Generated by Django 3.0.5 on 2020-08-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20200614_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfeature',
            name='layer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
