# Generated by Django 3.0.5 on 2020-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_location_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('music venue', 'music venue'), ('bar', 'bar'), ('park', 'park'), ('record store', 'record store'), ('musical instrument shop', 'musical instrument shop'), ('music lessons', 'music lessons'), ('recording studio', 'recording studio'), ('promo office', 'promo office'), ('workshop', 'workshop'), ('band house', 'band house'), ('empty plot', 'empty plot')], max_length=27),
        ),
    ]
