# Generated by Django 3.0.5 on 2020-08-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_locationfeature_layer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationfeature',
            options={'ordering': ['layer']},
        ),
        migrations.AlterField(
            model_name='locationfeature',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to='locations.Location'),
        ),
    ]
