# Generated by Django 3.0.5 on 2020-05-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20200503_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('concert hall', 'concert hall'), ('music bar', 'music bar'), ('local pub', 'local pub'), ('club', 'club'), ('record store', 'record store'), ('musical instrument shop', 'musical instrument shop'), ('music lessons', 'music lessons'), ('recording studio', 'recording studio'), ('promo office', 'promo office'), ('workshop', 'workshop'), ('band house', 'band house'), ('park', 'park'), ('empty plot', 'empty plot')], max_length=31)),
                ('category', models.CharField(choices=[('venue with stage', 'venue with stage'), ('pub or cafe', 'pub or cafe'), ('shop', 'shop'), ('public place', 'public place'), ('private place', 'private place'), ('training or work', 'training or work')], max_length=31)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Building'),
        ),
    ]
