# Generated by Django 3.0.5 on 2020-08-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_locationfeature_tech'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationFeature',
        ),
    ]
