# Generated by Django 3.0.5 on 2020-05-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20200503_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Building',
            new_name='BuildingType',
        ),
    ]
