# Generated by Django 3.0.5 on 2020-05-03 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtype_class_name'),
        ('locations', '0015_auto_20200503_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='building',
            new_name='building_type',
        ),
        migrations.CreateModel(
            name='BuildingEventSuitability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitability', models.CharField(choices=[('0', 'highly inappropriate'), ('1', 'very inappropriate'), ('2', 'inappropriate'), ('3', 'random!'), ('4', 'a bit odd'), ('5', 'fair'), ('6', 'fine'), ('7', 'apt'), ('8', 'very apt'), ('9', 'a perfect fit')], max_length=1)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.BuildingType')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventType')),
            ],
        ),
    ]
