# Generated by Django 3.0.5 on 2020-05-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtype_class_name'),
        ('locations', '0016_auto_20200503_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildingEventSuitability',
            new_name='VenueAssessment',
        ),
    ]
