# Generated by Django 3.0.5 on 2020-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0020_auto_20200510_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='entry_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
