# Generated by Django 3.0.5 on 2020-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_location_entry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='influence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
