# Generated by Django 3.0.5 on 2020-05-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0022_location_influence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='location',
            name='slots',
        ),
    ]
